version: 0.2

phases:
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:5 .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:5

environment_variables:
  plaintext:
    AWS_REGION: 'ap-southeast-1'
    ECR_REPO_URI: '590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app'

