version: 0.2
phases:
  build:
    commands:
      - docker build -t 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:3 .
      - docker push 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:3
