apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 590183700244.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app:latest
        ports:
        - containerPort: 8000

