apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default  # Same namespace as the deployment
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000
  type: LoadBalancer  # Exposes the service externally
